name: Deploy

on:
  push:

jobs:

  bot-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd bot 
          pip install -r requirements.txt
          pip install pytest pytest-asyncio

      - name: Run unit tests
        run: |
          cd bot
          pytest -v
  
  deploy:
    if: github.ref == 'refs/heads/main'

    needs:
      - bot-unit-tests

    runs-on: ubuntu-latest

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Trigger webhook
        run: |
          curl -X POST http://${{ secrets.SERVER_IP }}:9000/hooks/deploy-bot
